<?php

namespace AppBundle\Repository;

/**
 * FacilitatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacilitatorRepository extends \Doctrine\ORM\EntityRepository
{
}
