security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    providers:
        in_memory:
            memory:
                users:
                    ryan:
                        password: $2y$12$usOhoTOeAolym6//RPN1KOkdh7uRAf8sIfpMXDK3a3qrBzbGTgZFC
                        roles: 'ROLE_USER'
                    admin:
                        password: $2y$12$Xrby3THRABsoJx0Yv07lpusNpBlqTG8LL4IFJ18e/KdeGW53K2e3m
                        roles: 'ROLE_ADMIN'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~

            form_login:
                login_path: login
                check_path: login
                default_target_path: dashboard_index

            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: IS_AUTHENTICATED_FULLY }
